---
title: "Module 3 Instructor Notes"
author: "Carolyn Koehn"
format: pdf
---

# Data

## `producers_race_2017_ID.csv`

These data were downloaded from the [USDA NASS QuickStats tool](https://quickstats.nass.usda.gov/) with the following parameters:

- Program: CENSUS
- Sector: DEMOGRAPHICS
- Group: PRODUCERS
- Commodity: PRODUCERS
- Category: PRODUCERS   
- Data Item: 
  - PRODUCERS, (ALL) - NUMBER OF PRODUCERS
  - PRODUCERS, (ALL), FEMALE - NUMBER OF PRODUCERS
  - PRODUCERS, (ALL), MALE - NUMBER OF PRODUCERS
  - PRODUCERS, AMERICAN INDIAN OR ALASKA NATIVE - NUMBER OF PRODUCERS
  - PRODUCERS, ASIAN - NUMBER OF PRODUCERS
  - PRODUCERS, BLACK OR AFRICAN AMERICAN - NUMBER OF PRODUCERS
  - PRODUCERS, HISPANIC - NUMBER OF PRODUCERS
  - PRODUCERS, NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER - NUMBER OF PRODUCERS
  - PRODUCERS, WHITE - NUMBER OF PRODUCERS
- Domain: TOTAL
- Geographic Level: COUNTY
- State: IDAHO
- Year: 2017

## `commodities_ID_2017.csv`

These data were downloaded from the [USDA NASS QuickStats tool](https://quickstats.nass.usda.gov/) with the following parameters:

- Program: CENSUS
- Sector: CROPS
- Group: All
- Commodity: All
- Category: 
  - AREA BEARING
  - AREA HARVESTED
- Data Item: All
- Domain: TOTAL
- Geographic Level: COUNTY
- State: IDAHO
- Year: 2017

## `num_farms_areafiltered_tenure_1997_2017_ID.csv`

These data were downloaded from the [USDA NASS QuickStats tool](https://quickstats.nass.usda.gov/) with the following parameters:

- Program: CENSUS
- Sector:
  - DEMOGRAPHICS
  - ECONOMICS
- Group: FARMS & LAND & ASSETS
- Commodity: FARM OPERATIONS
- Category: OPERATIONS
- Data Item: FARM OPERATIONS - NUMBER OF OPERATIONS
- Domain: 
  - AREA OPERATED
  - TENURE
  - TOTAL
- Geographic Level: COUNTY
- State: IDAHO
- Year: 
  - 1997
  - 2017

And were cleaned with the following code:

```{r}
#| eval: false

# data file downloaded from QuickStats
size <- read.csv("data/num_farms_area_tenure_1997_2017_ID.csv") 

size_filt <- 
  dplyr::filter(size, 
                Domain.Category %in% 
                  unique(size[which(size$Year == 1997), "Domain.Category"]))

write.csv(size_filt, "data/num_farms_areafiltered_tenure_1997_2017_ID.csv")
```


# Teaching notes

- In this module, students start to manipulate whole columns instead of single numbers. They may miss this transition if they aren't reading the handout.
- I had students add the data for their counties to a shared Google sheet so that students could compare their counties with others. You may wish to record data in a different way. If you do, you will want to find and replace mentions of the shared Google sheet throughout these modules.
- I had students email me their finished PDFs. If you have a different way of collecting assignments, you will want to change the instructions at the end of the module to reflect that.