---
title: "Module 6 Instructor Notes"
author: "Carolyn Koehn"
format: pdf
---

# Data

All instructions to download data are in handout

# Teaching notes

- At this point, students are given the creative freedom to explore datasets and find new insights. In our research team, we also used a living document where I recorded any ideas for data to look at as they came up in discussions, so students had a starting point if they didn't have ideas themselves.
- In the American Community Survey section, it is stated that the ACS is available from 2009-2023. The range may need updating if using after the publication of these modules (May 2025).
- I had students add the data for their counties to a shared Google sheet so that students could compare their counties with others. You may wish to record data in a different way. If you do, you will want to find and replace mentions of the shared Google sheet throughout these modules.
- I had students email me their finished PDFs. If you have a different way of collecting assignments, you will want to change the instructions at the end of the module to reflect that.